apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomyapp-host
spec: 
  hostname: playeconomyapp.westus.cloudapp.azure.com
  acmeProvider: 
    email: sneha.basnet2@gmail.com
  tlsSecret: 
    name: playeconomyapp-tls
    