apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomyapp-host
  namespace: emissary
spec:
  hostname: gameplayeconomy.com
  tlsSecret:
    name: playeconomyapp-tls
  
    
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomyapp-host-www
  namespace: emissary
spec:
  hostname: www.gameplayeconomy.com
  tlsSecret:
    name: playeconomyapp-tls
  