apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: identity-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /identity-svc/
  service: identity-service.identity
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: catalog-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /catalog-svc/
  service: catalog-service.catalog
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: inventory-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /inventory-svc/
  service: inventory-service.inventory
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: trading-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /trading-svc/
  service: trading-service.trading
  allow_upgrade:
    - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: frontend-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /
  service: frontend-client.frontend

---
# frontend at www
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: frontend-root-www
  namespace: emissary
spec:
  hostname: www.gameplayeconomy.com
  prefix: /
  service: frontend-client.frontend  
---


apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: seq-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /seq/
  service: seq.observability
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: jaeger-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /jaeger/
  rewrite: ""
  service: jaeger-query.observability:16686
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prometheus-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /prometheus/
  service: prometheus-operated.observability:9090
  
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grafana-mapping
spec:
  hostname: gameplayeconomy.com
  prefix: /grafana/
  rewrite: ""
  service: prometheus-grafana.observability
