apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playeconomy-01-tls-cert
spec:
  secretName: playeconomy-tls
  issuerRef: 
   name: letsencrypt-prod
   kind: ClusterIssuer
  dnsNames:
    - "playeconomy-01.westus.cloudapp.azure.com"