apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{.Values.microserviceName}}-servicemonitor"
  labels: 
    appType: {{ .Chart.Name }}
spec: 
  selector: 
    matchLabels:
      appTypes: {{ .Chart.Name}}
  endpoints: 
    - port : http 